version: '3.8' # docker-composeのバージョン
services:
  spring-app: # Springアプリケーションのサービスに関する設定
    build: # コンテナイメージのビルドに使用する設定
      context: . # 現在のディレクトリ（本ファイルが配置されているディレクトリ）をコンテキストとして設定する。
      dockerfile: Dockerfile # 現在のディレクトリにあるDockerfileをイメージのビルドに使用する。
    ports:
      - "8080:8080" # ローカルの8080ポートと、コンテナ内の8080ポートを接続する。
    depends_on:
      - db # spring-appサービスはdbサービスが起動してから実行されるようにする。

  db: # MySQLのサービスに関する設定
    image: mysql:8.0 # 使用するDockerイメージ
    container_name: mysql # コンテナ名
    ports:
      - ${DB_PORT}:3306 # ローカルの該当ポートと、コンテナ内の3306ポートを接続する。
    environment: # MySQLの初期設定を定義する環境変数
      MYSQL_DATABASE: ${DB_NAME} # DB名
      MYSQL_USER: ${DB_USER} # DBのユーザー名
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS} # DBのルートパスワード
      MYSQL_PASSWORD: ${DB_PASS} # DBのパスワード
      TZ: ${TZ} # タイムゾーン
    volumes:
      - db-data:/var/lib/mysql # コンテナの /var/lib/mysql ディレクトリ（MySQL のデータが保存される場所）をホストにマウント。
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf # コンテナのdb設定ファイル /etc/mysql/conf.d/my.cnf を、ローカルの ./conf/my.cnf へマウント
      - ./initdb.d:/docker-entrypoint-initdb.d # 初期テーブルの作成とレコード投入をする。
volumes:
  db-data: # 名前付きボリューム