spring:
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  config:
    import: optional:file:.env[.properties]

logging:
  level:
    org:
      springframework:
        security: DEBUG